# Generated by Django 5.1.2 on 2024-11-02 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_readingprogress_current_chapter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParagraphView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('view_order', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.chapter')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.paragraph')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'view_order'],
                'unique_together': {('user', 'view_order')},
            },
        ),
    ]
