# Generated by Django 5.1.2 on 2024-11-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_paragraph_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='text_with_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
