# Generated by Django 5.1.2 on 2024-11-02 06:14

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_paragraph_text_with_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='text_with_links',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
