# Generated by Django 5.1.2 on 2024-11-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_reader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='chain',
            new_name='wallet_chain',
        ),
    ]
