# Generated by Django 5.1.2 on 2024-11-02 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_rename_chain_reader_wallet_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='user',
        ),
        migrations.AddField(
            model_name='reader',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
